### ISSUE TITLE
Change footer font color

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/toursbloom-web#15]
Change footer font color to be all white (#ffffff)

![image](https://user-images.githubusercontent.com/30463117/161916224-f3b12f3f-408b-40f0-9f67-d3aacba3c3f9.png)

**Comment by russel0907** [comment]
Change footer font color accordingly;

![Screenshot (233)](https://user-images.githubusercontent.com/94702093/161932115-69084117-4256-4f9c-8f6e-731a8997a04e.png)
