### ISSUE TITLE
Plan website content

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/toursbloom-web#17]
- [x] find similar tours management system website for inspiration
- [x] create web content mockup (using Figma/Adobe XD)

Example: 
https://www.youtube.com/watch?app=desktop&v=BUlJSfr3DVE&feature=youtu.be
https://play.google.com/store/apps/details?id=com.trekksoft.mpos
https://www.trekksoft.com/

**Comment by russel0907** [comment]
Plan website content;

![Toursbloom](https://user-images.githubusercontent.com/94702093/162662313-13749ef4-2ea6-4456-90f0-41e195e1dd86.png)
