### ISSUE TITLE
FIx web responsiveness in mobile view

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/toursbloom-web#20]
- [x] make logo left-align on mobile view
- [x] make title "Welcome to Toursbloom" have smaller font, less bold

<img width="489" alt="Screenshot 2022-04-12 at 10 38 05 PM" src="https://user-images.githubusercontent.com/30463117/162987789-df59a9f8-1169-402a-9738-0440c5d4a027.png">

**Comment by russel0907** [comment]
Fix web responsiveness in mobile view;

max-width 390px;
![Toursbloom](https://user-images.githubusercontent.com/94702093/163086584-3996f3a0-48ca-455c-9b44-875d5449e2b6.png)

max-width 375px;
![Toursbloom (1)](https://user-images.githubusercontent.com/94702093/163086607-78d8fec3-ed20-40e9-b094-941fd7f35d38.png)
