### ISSUE TITLE
Add logo on tab

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/toursbloom-web#22]
<img width="153" alt="Screenshot 2022-04-12 at 10 44 40 PM" src="https://user-images.githubusercontent.com/30463117/162989109-96947c72-433f-4433-b252-5f60c3e74e52.png">

Toursbloom icon file:
![toursbloom-icon](https://user-images.githubusercontent.com/30463117/162989226-3400d13e-51ad-44c3-9e48-5421278fa218.png)

**Comment by russel0907** [comment]
Add logo on tab;

![Screenshot (255)](https://user-images.githubusercontent.com/94702093/163296007-babc7dc2-9590-48ee-a27a-25677ebf4f45.png)
