### ISSUE TITLE
Make menu bigger

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/toursbloom-web#23]
- [x] Redesign menu to fill in web width.
- [x] change "Services" to "Features"

![image](https://user-images.githubusercontent.com/30463117/162989548-09963f81-65b4-4f5b-bd0f-17a1f98fecf4.png)

**Comment by russel0907** [comment]
Make menu bigger;

1. Redesign menu to fill in web width.
2. change "Services" to "Features"

![Screenshot (257)](https://user-images.githubusercontent.com/94702093/163525017-41d8ee4a-dc20-4b3b-b984-0bd443daaf02.png)
