### ISSUE TITLE
Redesign header

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/toursbloom-web#32]
![image](https://user-images.githubusercontent.com/30463117/171550707-4f90a085-62b1-40e0-901b-deaf552fee8f.png)

**Comment by russel0907** [comment]
## Redesign header;
Optimized Image size

## Web view
![Screenshot 2022-06-02 at 16-58-50 Toursbloom](https://user-images.githubusercontent.com/94702093/171627206-f7ae6603-eeed-4853-acd0-adc9d99d5f9c.png)

## Ipad View
![Screenshot 2022-06-02 at 17-02-15 Toursbloom](https://user-images.githubusercontent.com/94702093/171627213-d2977a35-eb0c-4bf7-ae06-199272b876a6.png)

## Mobile View
![Screenshot 2022-06-02 at 17-03-59 Toursbloom](https://user-images.githubusercontent.com/94702093/171627231-aa4f92af-694b-4362-a592-4dac9084fe53.png)
