### ISSUE TITLE
Fix screenshot for mobile view

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/toursbloom-web#33]
![Screen Shot 2022-06-02 at 13 20 07](https://user-images.githubusercontent.com/30463117/171558234-095a8eef-2be1-401c-932d-6502e0b0e369.png)

**Comment by russel0907** [comment]
## Fix screenshot for mobile view #33 
**1. Fix responsive view
2. Fix overlap background image
3. Fix responsive padding**

## Web 
![Screenshot (355)](https://user-images.githubusercontent.com/94702093/171824664-916e2676-3be1-4e0b-ba44-e8f46a11e2d5.png)

## Ipad
![127 0 0 1_5501_index html(iPad Air)](https://user-images.githubusercontent.com/94702093/171824642-ed65549b-477e-4a44-95ab-712e2caaa0fe.png)

## Mobile
![127 0 0 1_5501_index html(iPhone 12 Pro)](https://user-images.githubusercontent.com/94702093/171824636-c4af6a5b-859b-4f09-99c6-cfef72bfb19d.png)
