### ISSUE TITLE
Redesign how screenshot is displayed

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/toursbloom-web#39]
![image](https://user-images.githubusercontent.com/30463117/172512582-a4227244-686a-48a4-b768-b4942ef65022.png)

You can view the website below for inspiration:
https://www.spendesk.com/
https://www.circula.com/en

**Comment by russel0907** [comment]
**1. Redesign Features
2. Change Web Fonts
3. Design and Fix Mobile View responsiveness**

## Web View
![Screenshot (357)](https://user-images.githubusercontent.com/94702093/172603267-6db2cea2-86ad-4df1-8e0a-15e21d4901af.png)


# Mobile View
![Screenshot (358)](https://user-images.githubusercontent.com/94702093/172603312-7780af9c-8f50-4b3f-b175-ae56343c6b60.png)
