### ISSUE TITLE
Change screenshot design

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/toursbloom-web#41]
Change the screenshot photo & design. Now the screenshot doesn't look very pleasing.

![image](https://user-images.githubusercontent.com/30463117/172747088-59ed372d-8be0-4856-b876-4b54dad9c860.png)

**Comment by russel0907** [comment]
**Change screenshot design;**
**1. Also Added screenshot design with no tags**
**2. Fix screenshot design that cannot be seen in other browser**

## Web View
![Screenshot 2022-06-09 at 16-26-15 Toursbloom](https://user-images.githubusercontent.com/94702093/172803217-950eabf2-8f16-4ea3-bf35-a1366c60465c.png)

## Ipad View
![Screenshot 2022-06-09 at 16-25-45 Toursbloom](https://user-images.githubusercontent.com/94702093/172803337-5b5ca93d-458a-4d50-97dd-1c7598a9167b.png)

## Mobile View
![Screenshot 2022-06-09 at 16-26-58 Toursbloom](https://user-images.githubusercontent.com/94702093/172803374-702a1f21-ed12-4723-a308-b51d73cd9ccf.png)
