### ISSUE TITLE
Find template

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/toursbloom-web#47]
Find other template for the ticketing and booking management system. Suggest the template below.

**Comment by russel0907** [comment]
@rosclaritha 

## Template 1
https://technext.github.io/soffer/

## Template 2
https://technext.github.io/tivo/index.html

## Template 3
https://technext.github.io/app/index.html

## Template 4
https://technext.github.io/ultim8/index.html

## Template 5
https://technext.github.io/webhost/index.html

## Template 6
https://technext.github.io/beam/index.html
