### ISSUE TITLE
update header design

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/toursbloom-web#50]
https://www.toursbloom.com/
![image](https://github.com/phisoft/toursbloom-web/assets/30463117/d4e2413c-2d09-42a2-a5ac-48211924ad9a)

**Comment by abigailtaruc** [comment]
![image](https://github.com/phisoft/toursbloom-web/assets/110286983/e054713e-937b-4306-93a4-ab826fdf5955)
![image](https://github.com/phisoft/toursbloom-web/assets/110286983/39b3caeb-4cf6-484f-a2a0-ae9c4b1fce63)

**Comment by rosclaritha** [comment]
@abigailtaruc use this design:
![image](https://github.com/phisoft/toursbloom-web/assets/30463117/d98c5f1d-baa5-4027-880c-c9fca15938f4)
