### ISSUE TITLE
update footer design & info

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/toursbloom-web#52]
- [ ] update design

- [ ] update content
use [info@toursbloom.com](mailto:info@toursbloom.com) for email
phone use 0128731819
![image](https://github.com/phisoft/toursbloom-web/assets/30463117/2b7215c9-917a-49ab-94b7-731126e0240a)

**Comment by abigailtaruc** [comment]
![image](https://github.com/phisoft/toursbloom-web/assets/110286983/cce4d324-bd68-4580-9eb4-74342cd29296)
![image](https://github.com/phisoft/toursbloom-web/assets/110286983/94e3603b-3a9d-44ca-af87-88c09de96bc8)
