### ISSUE TITLE
update features design & content

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/toursbloom-web#58]
![image](https://github.com/phisoft/toursbloom-web/assets/30463117/adcd0cf4-05cb-4db0-9f3f-47efb7194b11)

**Comment by abigailtaruc** [comment]
![image](https://github.com/phisoft/toursbloom-web/assets/110286983/07afa7a8-1fc3-4b44-bb99-8ce5f24e8473)
![image](https://github.com/phisoft/toursbloom-web/assets/110286983/7a34134e-3aab-40aa-a0fb-84c86c60f679)
